// AUTO-GENERATED by scripts/sync-events.mjs
// Do not edit by hand — use the Keystatic admin at /keystatic
// Last generated: 2026-05-28T02:18:41.272Z

export type Announcement = { id: string; title: string; message: string; active: boolean; link_label?: string; link_url?: string }

export const generatedAnnouncements: Announcement[] = []
