// AUTO-GENERATED by scripts/sync-events.mjs
// Do not edit by hand — use the Keystatic admin at /keystatic
// Last generated: 2026-05-28T02:18:41.272Z

export type DtsReading = { title: string; author: string; description: string; current_chapters: string; next_chapters: string; quote: string; quote_attribution: string }

export const generatedDtsReading: DtsReading = {
  "title": "On the Incarnation",
  "author": "St. Athanasius of Alexandria",
  "description": "Athanasius' 4th-century defense of the Incarnation — why God became human in Jesus Christ. C.S. Lewis called it one of the greatest works of Christian theology.",
  "current_chapters": "Introduction & Chapters 1–3",
  "next_chapters": "Chapters 4–6",
  "quote": "For the Word of God came in His own Person, because it was He alone, the Image of the Father, Who could recreate man made after the Image.",
  "quote_attribution": "St. Athanasius — On the Incarnation, Chapter 3"
}
