// AUTO-GENERATED by scripts/sync-events.mjs
// Do not edit by hand — use the Keystatic admin at /keystatic
// Last generated: 2026-05-28T02:18:41.268Z

import type { RawEventData } from './events'

export const generatedEvents: RawEventData[] = [
  {
    "id": "coffee-june-11",
    "title": "Coffee & Conversation",
    "date": "2026-06-11",
    "time": "10:00 AM",
    "location": "Topeca Coffee, Tulsa",
    "university": "tu",
    "category": "social",
    "description": "Informal gathering for University of Tulsa students. Drop in anytime between 10-12 for coffee and conversation with Fr. Thom."
  },
  {
    "id": "compline-june-4",
    "title": "Compline at ORU",
    "date": "2026-06-04",
    "time": "9:00 PM",
    "location": "Christ Chapel, ORU Campus",
    "university": "oru",
    "category": "worship",
    "description": "End your day with the ancient Night Prayer of the Church. A quiet, contemplative service of psalms, Scripture, and silence."
  },
  {
    "id": "dts-june-10",
    "title": "Dead Theologians Society",
    "date": "2026-06-10",
    "time": "7:00 PM",
    "location": "St. John's Episcopal Church",
    "university": "both",
    "category": "dts",
    "description": "Continuing our reading of Augustine's Confessions. This week: Book IX and the death of Monica."
  },
  {
    "id": "dts-june-17",
    "title": "Dead Theologians Society",
    "date": "2026-06-17",
    "time": "7:00 PM",
    "location": "St. John's Episcopal Church",
    "university": "both",
    "category": "dts",
    "description": "We begin reading Athanasius' On the Incarnation. C.S. Lewis called it 'a masterpiece.' Come see why."
  },
  {
    "id": "dts-june-3",
    "title": "Dead Theologians Society",
    "date": "2026-06-03",
    "time": "7:00 PM",
    "location": "St. John's Episcopal Church",
    "university": "both",
    "category": "dts",
    "description": "Join us as we discuss Augustine's Confessions, Book VIII. This week we explore the nature of conversion and the will. Dinner provided."
  },
  {
    "id": "eucharist-june-14",
    "title": "Eucharist & Lunch",
    "date": "2026-06-14",
    "time": "12:00 PM",
    "location": "ORU Campus Ministry Center",
    "university": "oru",
    "category": "worship",
    "description": "Midday Eucharist followed by lunch together. A chance to receive communion and share a meal in community."
  },
  {
    "id": "evening-prayer-june-8",
    "title": "Evening Prayer",
    "date": "2026-06-08",
    "time": "5:30 PM",
    "location": "Sharp Chapel, University of Tulsa",
    "university": "tu",
    "category": "worship",
    "description": "Vespers from the Book of Common Prayer. A 30-minute service of psalms, canticles, and prayers."
  },
  {
    "id": "formation-june-15",
    "title": "Formation Class: Prayer",
    "date": "2026-06-15",
    "time": "6:00 PM",
    "location": "St. John's Parish Hall",
    "university": "both",
    "category": "formation",
    "description": "Part 3 of our summer formation series. This week: The Daily Office and the rhythm of prayer. Open to all."
  },
  {
    "id": "retreat-june-20",
    "title": "Summer Retreat",
    "date": "2026-06-20",
    "time": "5:00 PM",
    "location": "Camp Egan, Tahlequah",
    "university": "both",
    "category": "formation",
    "description": "Weekend retreat for all Cranmer House students. Theme: 'Rooted and Grounded in Love.' Cost: $50 (scholarships available)."
  },
  {
    "id": "service-saturday-june-6",
    "title": "Service Saturday",
    "date": "2026-06-06",
    "time": "9:00 AM",
    "location": "Meet at St. John's",
    "university": "both",
    "category": "service",
    "description": "Monthly service project with our community partners. This month: food pantry assistance at the Episcopal Center."
  }
]
