// AUTO-GENERATED by scripts/sync-events.mjs
// Do not edit by hand — use the Keystatic admin at /keystatic
// Last generated: 2026-05-28T02:18:41.271Z

export type PastReading = { id: string; work: string; author: string; period: string }

export const generatedPastReadings: PastReading[] = [
  {
    "id": "confessions",
    "work": "Confessions",
    "author": "St. Augustine",
    "period": "4th Century"
  },
  {
    "id": "life-together",
    "work": "Life Together",
    "author": "Dietrich Bonhoeffer",
    "period": "20th Century"
  },
  {
    "id": "on-the-incarnation",
    "work": "On the Incarnation",
    "author": "St. Athanasius",
    "period": "4th Century"
  },
  {
    "id": "revelations-of-divine-love",
    "work": "Revelations of Divine Love",
    "author": "Julian of Norwich",
    "period": "14th Century"
  },
  {
    "id": "the-imitation-of-christ",
    "work": "The Imitation of Christ",
    "author": "Thomas à Kempis",
    "period": "15th Century"
  },
  {
    "id": "the-screwtape-letters",
    "work": "The Screwtape Letters",
    "author": "C.S. Lewis",
    "period": "20th Century"
  }
]
