// AUTO-GENERATED by scripts/sync-events.mjs
// Do not edit by hand — use the Keystatic admin at /keystatic
// Last generated: 2026-05-28T02:18:41.272Z

export type SiteSettings = { chaplain_email: string; instagram_url: string; facebook_url: string; giving_url: string; mailing_address: string }

export const generatedSettings: SiteSettings = {
  "chaplain_email": "frthom@cranmerhouse.org",
  "instagram_url": "https://instagram.com/cranmerhouse",
  "facebook_url": "https://facebook.com/cranmerhouse",
  "giving_url": "",
  "mailing_address": "St. John's Episcopal Church\n4200 S. Atlanta Pl.\nTulsa, OK 74105"
}
