/**
 * Reads all Keystatic content and generates client-safe TypeScript files.
 *
 * Collections  → content/{name}/*.json     → lib/{name}-generated.ts
 * Singletons   → content/{name}/index.json → lib/{name}-generated.ts
 *
 * Runs automatically before every dev start and production build via package.json scripts.
 */

import fs from 'fs'
import path from 'path'
import { fileURLToPath } from 'url'

const __dirname = path.dirname(fileURLToPath(import.meta.url))
const root = path.join(__dirname, '..')

// ─── helpers ────────────────────────────────────────────────────────────────

function readJsonDir(dir) {
  if (!fs.existsSync(dir)) return []
  return fs.readdirSync(dir)
    .filter(f => f.endsWith('.json'))
    .sort()
    .map(f => {
      const raw = JSON.parse(fs.readFileSync(path.join(dir, f), 'utf8'))
      return { id: f.replace('.json', ''), ...raw }
    })
}

function readJsonFile(filePath) {
  if (!fs.existsSync(filePath)) return null
  return JSON.parse(fs.readFileSync(filePath, 'utf8'))
}

function writeGenerated(outputFile, typeOrImport, exportStatement) {
  const lines = [
    `// AUTO-GENERATED by scripts/sync-events.mjs`,
    `// Do not edit by hand — use the Keystatic admin at /keystatic`,
    `// Last generated: ${new Date().toISOString()}`,
    ``,
    typeOrImport,
    ``,
    exportStatement,
    ``,
  ]
  fs.writeFileSync(outputFile, lines.join('\n'))
}

// ─── events (collection) ────────────────────────────────────────────────────

const eventsDir = path.join(root, 'content', 'events')
const eventsOut = path.join(root, 'lib', 'events-generated.ts')

if (!fs.existsSync(eventsDir)) {
  fs.writeFileSync(eventsOut, 'export const generatedEvents: import("./events").RawEventData[] = []\n')
} else {
  const events = readJsonDir(eventsDir)
  writeGenerated(
    eventsOut,
    `import type { RawEventData } from './events'`,
    `export const generatedEvents: RawEventData[] = ${JSON.stringify(events, null, 2)}`
  )
  console.log(`✓ Synced ${events.length} events → lib/events-generated.ts`)
}

// ─── past readings (collection) ─────────────────────────────────────────────

const pastReadings = readJsonDir(path.join(root, 'content', 'past-readings'))
writeGenerated(
  path.join(root, 'lib', 'past-readings-generated.ts'),
  `export type PastReading = { id: string; work: string; author: string; period: string }`,
  `export const generatedPastReadings: PastReading[] = ${JSON.stringify(pastReadings, null, 2)}`
)
console.log(`✓ Synced ${pastReadings.length} past readings → lib/past-readings-generated.ts`)

// ─── announcements (collection) ─────────────────────────────────────────────

const announcements = readJsonDir(path.join(root, 'content', 'announcements'))
writeGenerated(
  path.join(root, 'lib', 'announcements-generated.ts'),
  `export type Announcement = { id: string; title: string; message: string; active: boolean; link_label?: string; link_url?: string }`,
  `export const generatedAnnouncements: Announcement[] = ${JSON.stringify(announcements, null, 2)}`
)
console.log(`✓ Synced ${announcements.length} announcements → lib/announcements-generated.ts`)

// ─── dts reading (singleton) ────────────────────────────────────────────────

const dtsReading = readJsonFile(path.join(root, 'content', 'dts-reading', 'index.json')) ?? {
  title: '',
  author: '',
  description: '',
  current_chapters: '',
  next_chapters: '',
  quote: '',
  quote_attribution: '',
}
writeGenerated(
  path.join(root, 'lib', 'dts-reading-generated.ts'),
  `export type DtsReading = { title: string; author: string; description: string; current_chapters: string; next_chapters: string; quote: string; quote_attribution: string }`,
  `export const generatedDtsReading: DtsReading = ${JSON.stringify(dtsReading, null, 2)}`
)
console.log(`✓ Synced DTS reading "${dtsReading.title}" → lib/dts-reading-generated.ts`)

// ─── settings (singleton) ───────────────────────────────────────────────────

const settings = readJsonFile(path.join(root, 'content', 'settings', 'index.json')) ?? {
  chaplain_email: 'frthom@cranmerhouse.org',
  instagram_url: 'https://instagram.com/cranmerhouse',
  facebook_url: 'https://facebook.com/cranmerhouse',
  giving_url: '',
  mailing_address: '',
}
writeGenerated(
  path.join(root, 'lib', 'settings-generated.ts'),
  `export type SiteSettings = { chaplain_email: string; instagram_url: string; facebook_url: string; giving_url: string; mailing_address: string }`,
  `export const generatedSettings: SiteSettings = ${JSON.stringify(settings, null, 2)}`
)
console.log(`✓ Synced site settings → lib/settings-generated.ts`)
